game/urls.py
from django.conf.urls import patterns, url

from game import views

urlpatterns = patterns(#'',
    url(r'^start/$', views.start_game, name='start_game'),
    url(r'^instructions/$', views.view_instructions, name='view_instructions'),
    url(r'^intentionality/$', views.intentionality, name='intentionality'),
    url(r'^no_player/$', views.no_player, name='no_player'),
    url(r'^round/start/$', views.start_round, name='start_round'),
    url(r'^round/play/$', views.play_round, name='play_round'),
    url(r'^round/end/$', views.end_round, name='end_round'),
    url(r'^questionnaire/$', views.questionnaire, name='questionnaire'),
    url(r'^demographic/$', views.demographic, name='demographic'),
    url(r'^thankyou/$', views.thankyou, name='thankyou'),
    url('', views.start_game, name='start_game')    
)

ultimatum_game/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^game/', include('game.urls', namespace="game")),
)

game/models.py
import logging
from django.core.exceptions import ValidationError
from django.db import models
from uuid import uuid1
import string
import random

logger = logging.getLogger(__name__)

def id_generator(size=12, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

class Kind(models.Model):
    ID_HUMAN = 'h'
    ID_COMPUTER = 'c'
    ID_ROBOT = 'r'
    ID_NONDETERMINISTIC = 'n'
    IDS = (
        (ID_HUMAN, 'Human'),
        (ID_COMPUTER, 'Computer'),
        (ID_ROBOT, 'Robot'),
        (ID_NONDETERMINISTIC, 'Randomness'),
    )

    id = models.CharField(max_length=1, choices=IDS, primary_key=True)

    def __unicode__(self):
        return self.get_id_display()

class Opponent(models.Model):
    # XXX: Beter way of storing this?
    kind = models.ForeignKey(Kind)
    picture = models.CharField(max_length=20)

    def __unicode__(self):
        return '<O(%s) %s>' % (self.kind, self.pk)

class Player(models.Model):
    MALE = False
    FEMALE = True
    GENDER = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )
    
    YES_NO = ((True, 'Yes'), (False, 'No'))

    registration_datetime = models.DateTimeField(auto_now_add=True)
    opponent_kind = models.ForeignKey(Kind)
    #opponents = models.ManyToManyField(Opponent)
    mturk_key = models.CharField(max_length=32, default=0, editable=False)
    start_time = models.IntegerField(default=-1)
    instructions_time = models.IntegerField(default=-1)
    questionnaire_time = models.IntegerField(default=-1)
    
    #gender = models.BooleanField(max_length=1, choices=GENDER)
    hours_a_day_you_spend_behind_a_computer = models.CharField(max_length=3)
    #robot_experience = models.BooleanField(choices=YES_NO)
    #ultimatum_experience = models.BooleanField(choices=YES_NO)
    age = models.CharField(max_length=3)
    nationality = models.CharField(max_length=50)

    # XXX: Express that all opponents should be of the same kind.

    def __unicode__(self):
        return '<P(%s) %s>' % (self.opponent_kind, self.pk)

class Round(models.Model):
    ACCEPT_CHOICES = ((True, 'Accept'), (False, 'Reject'))

    datetime = models.DateTimeField(auto_now=True)
    player = models.ForeignKey(Player)
    opponent = models.ForeignKey(Opponent)
    amount_offered = models.IntegerField()
    is_intentional = models.BooleanField()
    accepted = models.BooleanField(choices=ACCEPT_CHOICES, default=None)
    time_elapsed = models.IntegerField(default=-1)

    # XXX: Express that oppenent's kind matches player's selected opponent_kind.
    
    def clean(self):
        if self.accepted not in (True, False):
            raise ValidationError('The offer must be accepted or rejected explicitly.')

    def __unicode__(self):
        return '<R(%s) %s / %s / %s>' % (self.accepted, self.opponent, self.amount_offered, self.player)

class Question(models.Model):
    """Model for a question of the questionnaire."""
    text = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.text

class Option(models.Model):
    """Model for a possible answer to a question."""
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.text

class Answer(models.Model):
    """Model for an answer a user has given to a question."""
    player = models.ForeignKey(Player)
    question = models.ForeignKey(Question)
    #options = [o for o in Option.objects.all() if o.question==Question.objects.all()[2]]
    #choices = ((option.id, option.text) for option in options) 
    option = models.ForeignKey(Option)      
    
    def __unicode__(self):
        return '<A %s / %s / %s>' % (self.player, self.question, self.option)
    
    def generate_choices(self):
        question = self.question
        options = [o for o in Option.objects.all() if o.question==question]
        choices = ((option.id, option.text) for option in options)
        return choices

game/forms.py
from django.forms import Form, ModelForm, BooleanField, RadioSelect, HiddenInput

from game.models import Kind, Opponent, Player, Round, Question, Option, Answer

class OfferAcceptanceForm(ModelForm):
    class Meta:
        model = Round
        fields = ['accepted', 'time_elapsed']
        widgets = { 'accepted': RadioSelect, 'time_elapsed' : HiddenInput }

class QuestionnaireForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['option']
        widgets = { 'option': RadioSelect }
    
    #def clean_option(self):
    #    option = self.cleaned_data['option']
    #    return Option.objects.get(id=option)

class ReadForm(Form):
    checked = BooleanField(label='Check this box if you have read this carefully')

class DemographicForm(ModelForm):
    class Meta:
        model = Player
        fields = ['hours_a_day_you_spend_behind_a_computer', 'age', 'nationality',
                  #'gender', 'robot_experience', 'ultimatum_experience',
                 ]
        widgets = {'gender': RadioSelect, 'robot_experience': RadioSelect, 'ultimatum_experience': RadioSelect}

game/views.py
import logging
import random
import time

from django.core.urlresolvers import reverse
from django.db.models import Count, Min
from django.http import HttpResponseNotAllowed, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.core.paginator import Paginator, PageNotAnInteger

from game.models import Kind, Opponent, Player, Round, Question, Option, Answer
from game.forms import OfferAcceptanceForm, QuestionnaireForm, ReadForm, DemographicForm

from uuid import uuid1

# The amount of "money units" available in each round.
AMOUNT_AVAILABLE = 100
# The number of rounds.
NUM_ROUNDS = 8
# The number of questions per page in the questionnaire.
QUESTIONS_PER_PAGE = 5
# The minimum number of questions per page in the questionnaire.
QUESTION_ORPHANS = 2

logger = logging.getLogger(__name__)

# XXX: Must somehow ensure cookies are enabled?
# XXX: Must showhow ensure javascript is enabled.
# XXX: Should keep offer displayed once it's been uncovered. Timer must not be
#      reset.

# generate game/fixtures/initial_data.json
# python manage.py dumpdata game | json_pp
# XXX: Also delete players.
###############################################################################
# XXX: Is there a better way to ensure existence of all Kinds?
#for k in Kind.IDS:
#    Kind.objects.get_or_create(id=k[0])
##
### XXX: Is there a better way to generate all opponents?
#for k in Kind.objects.all():
#    for i in range(1, NUM_ROUNDS+1):
#        picture = '%s_%s' % (k.id, i)
#        Opponent.objects.get_or_create(kind=k, picture=picture)
###############################################################################

# XXX: Must enforce, per player, that intro and instructions have been viewed!

class HttpResponseSeeOther(HttpResponseRedirect):
    status_code = 303

def get_or_create_player(session):
    player, created = Player.objects.get_or_create(id=session.get('player_id', None),
        defaults={'opponent_kind': select_opponent_kind_for_new_player()})

    if created:
        session['player_id'] = player.id

    return player

def select_opponent_kind_for_new_player():
    # XXX: We select the opponent kind that has been assigned to the least
    # number of players. Note that *all* players are taken into consideration,
    # including those that did not yet finish or "abandoned" the experiment.
    # This is not optimal, but should converge to optimality in the limit. One
    # advantage of this approach over an approach that takes historical game
    # round data into account is that it has nicer characteristics if, after
    # _some_ rounds have already been played, a large number of people all of a
    # sudden start the experiment.
    kinds = Kind.objects.annotate(num_players=Count('player'))
    min_players = kinds.aggregate(min_players=Min('num_players'))['min_players']
    return random.choice(kinds.filter(num_players=min_players))

def get_opponent(session):
    # XXX: Use hasattr or something like that instead? If so, fix elsewhere as
    # well.
    opponent_id = session.get('opponent_id', None)
    return Opponent.objects.get(id=opponent_id) if opponent_id else None

def create_opponent(session, player):
    # Must not have more than one opponent concurrently.
    assert not get_opponent(session)

    # Determine eligible opponents.
    available_opponents = list(Opponent.objects.filter(kind=player.opponent_kind))
    for r in Round.objects.filter(player=player):
        # Can't play the same opponent twice.
        available_opponents.remove(r.opponent)

    if not available_opponents:
        # No opponents left.
        return None

    # XXX: Might have to select a RANDOM opponent; see
    # /opt/lampp/htdocs/ultimatum/index.php
    opponent = random.choice(available_opponents)
    session['opponent_id'] = opponent.id

    return opponent

def create_intent(session, player):
    choice = session.get('intent', random.choice([True, False]))
    session['intent'] = choice

    return choice

def get_or_create_offer(session, player, opponent):
    offer = session.get('amount_offered', None)
    if offer:
        # Already made an offer, but it was not yet accepted.
        return offer

    # XXX: This amount precisely matches the number of opponents of any given
    # kind. That correspondence must be made clearer!
    # XXX: Also, for some reason an offer of 40 was never made. We could easily
    # add two times 40. As long as the number of available options is equal to
    # or greater than the number of available opponents, there's no problem.
    # (Of course, during statistical analysis one must keep in mind that
    # players did not receive exactly the same offers.)
    if str(opponent.kind) != 'Randomness':
        available_offers = [10, 20, 30, 50]
        assert len(available_offers) * 2 == NUM_ROUNDS
    else:
        available_offers = [10, 10, 20, 20, 30, 30, 50, 50]
        assert len(available_offers)  == NUM_ROUNDS
        session['intent'] = False
        
    for r in Round.objects.filter(player=player, is_intentional=session['intent']):
        available_offers.remove(r.amount_offered)


    # XXX make nicer.
    assert available_offers

    # XXX: The original experiment hard-coded eight distinct offer sequences
    # that were "symmetric". The fourth and fifth offer would always be
    # identical. Our randomized appraoch doesn't guarantee any of these
    # properties. Is that a good or a bad thing?
    offer = random.choice(available_offers)
    session['amount_offered'] = offer

    return offer

def get_round_number(session, player):
    # Must have an opponent for this question to make sense.
    assert get_opponent(session)

    return len(Round.objects.filter(player=player)) + 1

def get_round_details(session, find_opponent=False):
    player = get_or_create_player(session)

    opponent = get_opponent(session)
    if not opponent and find_opponent:
        opponent = create_opponent(session, player)

    if opponent:
        round_number = get_round_number(session, player)
        logger.debug('Player %s plays round %d against %s' %
                     (player, round_number, opponent))
    else:
        round_number = None
        logger.debug('Player %s played all rounds' % player)

    return player, opponent, round_number

def is_first_subround(round_number):
    return round_number in {1, (NUM_ROUNDS / 2) + 1}

@require_GET
def start_game(request):
    request.session['start_time'] = time.time()
    return render(request, 'game/start_game.html', {})

@require_GET
def view_instructions(request):
    player = get_or_create_player(request.session)
    
    if player.instructions_time == -1:
        elapsed = (time.time() - request.session.get('start_time')) * 1000
        player.start_time = int(round(elapsed))
        player.save()

    request.session['instructions_time'] = time.time()

    if str(player.opponent_kind) == 'Randomness':
        page = 'game:no_player'
    else:
        page = 'game:intentionality'

    return render(request, 'game/view_instructions.html',
                  {'opponent_kind': str(player.opponent_kind),
                    'page' : page})
@require_GET
def no_player(request):
    return render(request, 'game/no_player.html', {})

@require_http_methods(["GET", "POST"])
def intentionality(request):
    player, opponent, round_number = get_round_details(request.session)
    
    form = ReadForm()
    logger.debug(request.POST.get('checked', False))
    if not is_first_subround(round_number):
        return HttpResponseSeeOther(reverse('game:start_round'))

    if 'viewed_intentionality' not in request.session:
        request.session['viewed_intentionality'] = []

    if request.method == 'POST' and request.POST.get('checked', False):
        request.session['viewed_intentionality'] += [round_number]
        return HttpResponseSeeOther(reverse('game:start_round'))
    
    choice = create_intent(request.session, player)
    
    if (round_number != 1):
        visited_intent = request.session.get('visited_intent', False)
        if not visited_intent:
            choice = not choice
            request.session['intent'] = choice
            request.session['visited_intent'] = True
    
    return render(request, 'game/intentionality.html',
                  {'intentionality': choice, 'form': form})

@require_GET
def start_round(request):
    player, opponent, round_number = get_round_details(request.session, True)

    if player.instructions_time == -1:
        elapsed = (time.time() - request.session.get('instructions_time')) * 1000
        player.instructions_time = int(round(elapsed))
        player.save()
    #if round_number in {1, (NUM_ROUNDS/2)+1} and not request.session.get('viewed', False):
    #    request.session['viewed'] = True
    #    return HttpResponseSeeOther(reverse('game:intentionality'))
    #else:
    #    request.session['viewed'] = False

    if not opponent:
        return HttpResponseSeeOther(reverse('game:questionnaire'))
         
    if is_first_subround(round_number) and not round_number in request.session.get('viewed_intentionality', []) and not str(opponent.kind) == 'Randomness':
        return HttpResponseSeeOther(reverse('game:intentionality'))

    return render(request, 'game/start_round.html',
                  {'round_number': round_number, 'opponent': opponent, 'picture': opponent.picture + '.jpg'})

@require_http_methods(["GET", "POST"])
def play_round(request):
    player, opponent, round_number = get_round_details(request.session)
    if not opponent:
        # The player has not yet been introduced to an opponent. That must
        # happen first.
        return HttpResponseSeeOther(reverse('game:start_round'))

    amount_offered = get_or_create_offer(request.session, player, opponent)
    round = Round(player=player, opponent=opponent, amount_offered=amount_offered,

game/templates/game/demographic.html
{% include "game/header.html" %}

<h1>Demographic questions</h1>
<p>Please fill in the following personal details.</p>
<form action="{% url 'game:demographic' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
 <input type="submit" value="Submit" />
</form>

{% include "game/footer.html" %}

game/templates/game/end_round.html
{% include "game/header.html" %}

<!-- Include test from /opt/lampp/htdocs/ultimatum/letsplayagame_showresult.php -->

<!-- XXX: Wrong. After last round we must not start again! -->
<h1>Round has ended</h1>
<p>This concludes the current round.</p>
{% if accepted %}
<p>You chose to accept. Therefore, you have gained {{ amount_offered }} MU.</p>
{% else %}
<p>You chose to reject. Therefore, you have not gained any money units this round.</p>
{% endif %}
<p>Click the button below to proceed.</p>
<form action="{% url 'game:start_round' %}" method="get">
  <input type="submit" value="Next page" />
</form>

{% include "game/footer.html" %}

game/templates/game/footer.html
  </body>
</html>

game/templates/game/header.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Experiment: Let's play a game!</title>
    <link rel="icon" type="image/x-icon" href="{% static "game/favicon.ico" %}" />
    <link rel="stylesheet" href="{% static "game/style.css" %}"/>
  </head>
  <body>

game/templates/game/intentionality.html
{% include "game/header.html" %}
{% load staticfiles %}
<h1>Let's play a game - about your next opponents</h1>
<h3>Important!!!</h3>
<p>In this part, opponents can  
{% if intentionality %}
  decide upon offers <strong>completely by themselves</strong>.
{% else %}
  only give you <strong>completely random</strong> offers.
{% endif %}
</p>

<form action="{% url 'game:intentionality' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Next page" />
</form>

{% include "game/footer.html" %}

game/templates/game/no_player.html
{% include "game/header.html" %}
<h1>Let's play a game</h1>
Unfortunately, we could not match you up with another player. This means you will not be playing against someone else. Instead, you will receive random offers that are generated by a program.

<form action="{% url 'game:start_round' %}" method="get">
  <input type="submit" value="Next Page" />
</form>

{% include "game/footer.html" %}

game/templates/game/play_round.html
{% include "game/header.html" %}
{% load staticfiles %}

<script type="text/javascript">
  var start;
  function setFormEnabled(isEnabled) {
    var inputs = document.getElementsByTagName('input');
    for (var i = 0; i < inputs.length; i++){
      inputs[i].disabled = !isEnabled;
    }
  }

  function showOffer() {
    document.getElementById('click_request').style.display = 'none';
    document.getElementById('click_response').style.display = 'block';
  }

  function startTime(e) {
    start = e.timeStamp;
  }

  function elapsed_time(e) {
     document.my_form.time_elapsed.value = e.timeStamp - start;
  }

</script>

<h1>Offer</h1>
<center><img src="{% static 'game/pictures/'|add:picture %}" alt="photo" style="width: 20%; height: 20%"/></center>
<p>{{ opponent_name }} has prepared an offer for you. Click the box below to see
how {{ opponent_name }} would like to divide the available
{{ amount_offered|add:amount_kept }} MU.</p>

<div id="offer_section" onclick="showOffer(); setFormEnabled(true); startTime(event);">
  <div id="click_request">
    <p>Click here to see {{ opponent_name }}'s offer.</p>
  </div>
  <div id="click_response">
    <p>You get <strong>{{ amount_offered }} MU</strong>.</p>
    <p>{{ opponent_name }} keeps {{ amount_kept }} MU.</p>
  </div>
</div>

<p>Indicate whether you want to <em>accept</em> or <em>reject</em> this
division, then click <em>Next Page</em> to continue.</p>

<form action="{% url 'game:play_round' %}" name="my_form" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div class="offer_response">
    {{ form.accepted }}
    {{ form.time_elapsed }}
  </div>
  <input onclick="elapsed_time(event);" type="submit" value="Next page" />
</form>

<script type="text/javascript">
  setFormEnabled(false);
</script>
{% include "game/footer.html" %}

game/templates/game/questionnaire.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Experiment: Let's play a game!</title>
    <link rel="icon" type="image/x-icon" href="{% static "game/favicon.ico" %}" />
    <link rel="stylesheet" href="{% static "game/styles2.css" %}"/>
  </head>
  <body>

<h1>Questionnaire</h1>
<p>Please fill in the questions below and click the button at the bottom of the page to continue.</p>
<div class="checkboxgroup">
<form action="{% url 'game:questionnaire' %}" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <ul id="questionnairemenu">
  {% for t in questions_forms %}
    <li><strong>{{ t.0.text }}</strong></li><p>
    {{ t.1.option }}<br></p>
  {% endfor %}
  </ul>
  <input type="submit" value="Next" />
</form>
</div>

  </body>
</html>

game/templates/game/start_game.html
{% include "game/header.html" %}
<h1>Welcome to the 'Let's play a game' experiment!</h1>

<p>This experiment is part of a study at the Human-Technology Interaction
department of the Eindhoven University of Technology. In this experiment you
will be playing several rounds of a simple game, followed by a number of
questions about yourself and some other topics. More information about the
nature and purpose of the experiment will be provided after completion of the
experiment.</p>

<p>You will receive a fixed cash reward for your participation. The money units (MU) used in this game are entirely fictional and exist only in the game context.</p>

<p>The experiment usually takes about 10 minutes to complete. Please make sure you
have enough time to finish the experiment before you start. Please make sure to avoid distractions, such as textual or auditory conversations, during the experiment.</p>

<p>Participation in this study is entirely voluntary and as such, you are free to
stop the experiment at any time.  Should you wish to do so, simply close the
browser window containing the experiment's web page. Note that you will only receive payment if
you complete the full experiment.</p>

<p>The data collected in this experiment will be handled anonymously and will be
used exclusively for scientific purposes.</p>

<p>If you have read and agree with the conditions above, you can confirm your
consent by pressing the 'Start' button at the bottom of the page.</p>

<em>Press 'Start' to begin the experiment.</em>

<form action="{% url 'game:view_instructions' %}" method="get">
  <input type="submit" value="Start" />
</form>

{% include "game/footer.html" %}

game/templates/game/start_round.html
{% include "game/header.html" %}
{% load staticfiles %}

<!-- Include test from /opt/lampp/htdocs/ultimatum/letsplayagame_showopponent.php -->

<h1>Opponent {{ round_number }}</h1>

<center><img src="{% static 'game/pictures/'|add:picture %}" alt="photo" /></center>

<p>Meet opponent {{ round_number }}, shown in the picture above.</p>
<p>You'll be playing against this opponent in the following round.</p>

<form action="{% url 'game:play_round' %}" method="get">
  <input type="submit" value="Next page" />
</form>

{% include "game/footer.html" %}

game/templates/game/thankyou.html
{% include "game/header.html" %}

<!-- Include test from /opt/lampp/htdocs/ultimatum/letsplayagame_showresult.php -->

<!-- XXX: Wrong. After last round we must not start again! -->
<h1>Thank you!</h1>
<p>Thanks for your participation. Your answers have been submitted.</p>
<p>In order to receive payment from MTurk, you should use the following code:</p>
<strong>{{ key }}</strong>

{% include "game/footer.html" %}

game/templates/game/view_instructions.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Experiment: Let's play a game!</title>
    <link rel="icon" type="image/x-icon" href="{% static "game/favicon.ico" %}" />
    <link rel="stylesheet" href="{% static "game/style3.css" %}"/>
  </head>
  <body>
<h1>Let's play a game - game instructions</h1>

<div><p style="float: left; margin-right: -80px;"><img src="{% static 'game/instructions/'|add:opponent_kind|add:'.png' %}" alt="photo" style="width: 80%; height: 80%" /></p>

<!-- Include test from /opt/lampp/htdocs/ultimatum/letsplayagame_gameinfo.php -->
<br />
<p>As mentioned on the previous page, the first part of this experiment consists of several rounds of a simple game. The game revolves around 'Money Units' ('MU'), the currency of the game.
Two players take part in the game: you and your opponent. The objective for both players is to gather MU. You will play eight rounds in total and face a <emph>different</emph> opponent in each round.</p>

<p>Each round consists of 3 steps:
<ol>
<li>A short introduction: you get to see a picture of the opponent you will face in this round.</li>
<li>A total amount of 100 MU is available at the start of the round. Your opponent gets to
propose a division of the available 100 MU between the players. <em>For instance, your opponent may propose that you yet 25 MU, keeping the remaining 75 MU.</em></li>
<li>After receiving this offer, you get to decide whether the deal goes through. You have two options: to accept the offer or to refect the offer.</li>
<ol type="a"><li><strong>Accept:</strong> If you accept the offer, the Money Units are distributed as proposed by your opponent. <em>Continuing the above example, you would get 25 MU and your opponent would get 75 MU.</em></li>
<li><strong>Reject:</strong> If you reject the offer, the deal is off. As a result, your opponent will receive no MU in this round, but it also means you give up your share and receive no MU in this round.</li></ol></ol></p>

<p>Note that you will only meet each of the opponents once and that neither you, nor the other
players, have any means of communicating with one another. What happens in each round
therefore stands alone and cannot inﬂuence or be inﬂuenced by other game rounds.
</p>
</div>

<em>Click 'Next page' to continue with the experiment and start the first round.</em>
<form action="{% url page %}" method="get">
  <input type="submit" value="Next page" />
</form>

  </body>
</html>